### ISSUE TITLE
Need Critters: true to work?

### ISSUE THREAD

**Issue by bronze** [PlayForm/Inline#111]
Hi there

I've recently updated to and don't know if this is intended, but critters only started working after defining critters: true on astro config.
```
"astro": "^2.5.5",
"astro-critters": "^1.1.35",
```
```
...
critters({
    critters: true,
    preload: 'body',
  }),
...
```

also, is it possible to change the preload strategy? i thought we could override any option there.

repo here if you wanna take a look: https://github.com/bronze/carlosbronze-com-br/tree/dev

cheers!

**Comment by NikolaRHristov** [comment]
Thank you, a critical bug has been introduced in [`1.1.35`](https://github.com/astro-community/astro-critters/releases/tag/v1.1.35), [`1.1.36`](https://github.com/astro-community/astro-critters/releases/tag/v1.1.36). These have been deprecated, this is fixed in [`1.1.37` ](https://github.com/astro-community/astro-critters/releases/tag/v1.1.37)

**Comment by NikolaRHristov** [comment]
The way you can override `critters` options in `astro-critters` is:

```ts
import critters from "astro-critters";
import { defineConfig } from "astro/config";

export default defineConfig({
	integrations: [
		critters({
			critters: {
				preload: "body",
			},
		}),
	],
});
```

`astro-critters` is just a wrapper over `critters`. Anything you put in `critters: {}` will get passed down to `critters`.

**Comment by NikolaRHristov** [comment]
I made a PR on your repo that addresses this.
