### ISSUE TITLE
CSS File Added Twice

### ISSUE THREAD

**Issue by austincollinpena** [PlayForm/Inline#117]
Hi there, 
```html
<link rel="stylesheet" href="/_astro/a.e72665bf.css" media="print" onload="this.media=&apos;all&apos;"><noscript><link rel="stylesheet" href="/_astro/a.e72665bf.css">
```

On my critters output, the CSS file is emitted twice. Once with the media="print" and one without.

How can I fix that?

Astro version: 2.6.4
Astro critters: 1.1.38

**Comment by kurtextrem** [comment]
Astro 2.6 also has the option `inlineStylesheets` to make this automatically happen. In my experience, `astro-critters` works better though (for a static build).

If you take a look at the output, it's not added twice; it's added 1x to lazy load the CSS (via `onload`) and the other one is wrapped in `<noscript>` for users with JS disabled.

**Comment by NikolaRHristov** [comment]
@austincollinpena This is expected behavior, this is how Critters decides which CSS to load. If you have JavaScript enabled in the browser it will load on the Window load event else it will fallback to the stylesheet inside the `<noscript>` tag. See https://github.com/GoogleChromeLabs/critters#preloadstrategy for more information.

**Comment by austincollinpena** [comment]
Thank you friends.
