### ISSUE TITLE
It keeps processing the same file

### ISSUE THREAD

**Issue by mbouclas** [PlayForm/Inline#94]
Hi and thank you for your work.
I'm running the extension on a fairly large project and i get the following behavior on every file. It seems to me that it outputs the same file again and again. The project has multiple routes and thousands of files and everyone of them in the end contain the same css. I have used your extension in other projects and never had this. Using your latest version, same goes for Astro. 
Another weird thing is that it ignores all options. For example:
```
      critters({
        exclude: [
          (file) => console.log('-------', file)
        ],
      }),
```
The above code does not output (as you can see on the logs bellow) the console.log. On a brand new small project it does, same package.json on both projects.

The output

```
Time 146.0939
4 rules skipped due to selector errors:
  .prose :where(hr + *):not(:where([class~="not-prose"] *)) -> Cannot read properties of undefined (reading 'type')
  .prose :where(h2 + *):not(:where([class~="not-prose"] *)) -> Cannot read properties of undefined (reading 'type')
  .prose :where(h3 + *):not(:where([class~="not-prose"] *)) -> Cannot read properties of undefined (reading 'type')
  .prose :where(h4 + *):not(:where([class~="not-prose"] *)) -> Cannot read properties of undefined (reading 'type')
Inlined 17.3 kB (30% of original 56.1 kB) of _astro/about-us.8647140a.css.
Inlined 82 B (3% of original 2.49 kB) of _astro/_...page_.0f08ca28.css.
Time 159.6
4 rules skipped due to selector errors:
  .prose :where(hr + *):not(:where([class~="not-prose"] *)) -> Cannot read properties of undefined (reading 'type')
  .prose :where(h2 + *):not(:where([class~="not-prose"] *)) -> Cannot read properties of undefined (reading 'type')
  .prose :where(h3 + *):not(:where([class~="not-prose"] *)) -> Cannot read properties of undefined (reading 'type')
  .prose :where(h4 + *):not(:where([class~="not-prose"] *)) -> Cannot read properties of undefined (reading 'type')
Inlined 17.3 kB (30% of original 56.1 kB) of _astro/about-us.8647140a.css.
Inlined 82 B (3% of original 2.49 kB) of _astro/_...page_.0f08ca28.css.

```

Any ideas?

**Comment by NikolaRHristov** [comment]
This is because every file contains the "advanced" selector according to `critters`. I've had this problem too.

You can disable logging, but this is not an error that will break things.

```ts
import critters from "astro-critters";
import { defineConfig } from "astro/config";

export default defineConfig({
	integrations: [
		critters({ logger: 0 }),
	],
});
```

Also `astro-critters` goes through each of the HTML files individually not the CSS files. This is why you're receiving the same error. You have multiple HTML files using the same CSS file.

`critters` just doesn't know how to handle the selector from `@tailwindcss/typography` package. https://tailwindcss.com/docs/typography-plugin. You can open an issue at their repository https://github.com/GoogleChromeLabs/critters, but I doubt that there will be any fixes soon as it already seems that there is an issue on this exact topic - https://github.com/GoogleChromeLabs/critters/issues/103
